### ISSUE TITLE
Support versionCode/bundleVersion in upload options 

### ISSUE THREAD

**Issue by pdziak** [bugsnag/bugsnag-sourcemaps#48] opened 2019-10-23 14:05 UTC
### Expected behavior
As stated in docs: https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/ there is an option to set appVersionCode (android) and appBundleVersion (ios) when uploading by CURL.

### Observed behavior
Should be an option like --app-version-code and app-bundle-version. I know there are options named --code-bundle-id and --app-version but not always app version is incremented on update. Also providing an internal version of code Is much more convenient.

**Comment by mattdyoung** [comment] 2019-10-23 15:27
I believe this is a duplicate of https://github.com/bugsnag/bugsnag-sourcemaps/issues/47.

**Closed as completed by mattdyoung** 2019-10-23 15:27 UTC
Labels: duplicate
